def _agent(
    agent_id: str,
    domain: str,
    role: str,
    tools: list[str],
    memory: str,
    tier: str = "core",
    boundaries: list[str] | None = None,
) -> dict[str, object]:
    governed_tools = [*tools]
    if "governed_llm_router" not in governed_tools:
        governed_tools.append("governed_llm_router")
    return {
        "id": agent_id,
        "domain": domain,
        "tier": tier,
        "activation": "always_on_parallel" if tier == "core" else "on_demand_specialist",
        "role": role,
        "objective": role,
        "tools": governed_tools,
        "memory": memory,
        "context": f"Receives only {domain} context plus the orchestration summary and acceptance criteria.",
        "boundaries": boundaries or [
            "Do not bypass SDD gates.",
            "Do not perform destructive actions without explicit approval.",
            "Escalate cross-domain conflicts to orchestration-manager.",
        ],
        "success_criteria": [
            "Output is specific, testable, and aligned with the enterprise spec.",
            "Risks, assumptions, and required validations are stated.",
            "Artifacts are ready for downstream agents without broad context replay.",
        ],
    }


CORE_AGENT_CATALOG: list[dict[str, object]] = [
    _agent("orchestration-manager", "orchestration", "Routes work, owns swarm governance, anti-drift gates, and escalation.", ["ruflo_mcp", "workflow_registry", "memory_stats"], "semantic"),
    _agent("product-strategy", "product", "Business outcome, success metrics, acceptance criteria, and no-code project framing.", ["briefing", "acceptance_criteria"], "semantic"),
    _agent("data-engineering", "data", "Pipelines, ingestion, validation, lineage, and feature/data contracts.", ["data_contract", "dataset_treatment"], "semantic"),
    _agent("data-science", "analytics", "EDA, statistics, hypotheses, leakage checks, feature strategy, and metric interpretation.", ["statistics", "quality_gates"], "semantic"),
    _agent("machine-learning", "ml", "Dataset design, evaluation, training loops, monitoring, and model cards.", ["model_service", "mlflow", "model_card"], "semantic"),
    _agent("llm-engineering", "llm", "Prompt systems, tool use, evals, guardrails, and production LLM behavior.", ["prompt_registry", "tool_calling", "eval_service"], "semantic"),
    _agent("rag-engineering", "rag", "Chunking, retrieval, reranking, citations, and knowledge freshness.", ["rag_pipeline", "vector_index", "retrieval_evals"], "semantic"),
    _agent("backend-engineering", "backend", "FastAPI, service boundaries, repositories, API contracts, and reliability.", ["fastapi", "pydantic", "repositories"], "episodic"),
    _agent("frontend-engineering", "frontend", "Next.js, TypeScript, dashboards, agent/workflow/memory/swarm UX.", ["nextjs", "typescript", "dashboard"], "episodic"),
    _agent("integration-automation", "integration", "Codex, Ruflo, MCP, API connectors, local tools, and automation wiring.", ["ruflo_cli", "mcp", "api_connectors"], "episodic"),
    _agent("security-compliance", "security", "Auth, permissions, LGPD/privacy, policy checks, and safe autonomy limits.", ["api_key", "guardrails", "policy"], "semantic"),
    _agent("observability-ops", "operations", "Traces, cost, latency, token budget, drift, quality signals, and run health.", ["structured_logs", "metrics", "mlflow"], "episodic"),
    _agent("devops", "platform", "CI/CD, environments, secrets, observability, and deployment readiness.", ["docker", "validation_scripts", "deployment"], "episodic"),
    _agent("testing-qa", "quality", "Unit, integration, contract, E2E, regression, and adversarial tests.", ["pytest", "evals", "quality_gates"], "episodic"),
    _agent("documentation", "docs", "Architecture, onboarding, API, workflow, and runbook documentation.", ["runbooks", "architecture_docs", "checklists"], "episodic"),
]

SPECIALIST_AGENT_CATALOG: list[dict[str, object]] = [
    _agent("prompt-evaluator", "llm", "Evaluates prompts for quality, robustness, regressions, and safety.", ["prompt_registry", "eval_service"], "semantic", "specialist"),
    _agent("prompt-versioning", "llm", "Maintains prompt versions, changelogs, rollback points, and evaluation lineage.", ["prompt_registry", "release_checklist"], "episodic", "specialist"),
    _agent("tool-calling-engineer", "llm", "Designs safe tool calling flows, tool permissions, and tool result validation.", ["tool_registry", "guardrails"], "semantic", "specialist"),
    _agent("function-schema-designer", "llm", "Designs typed function schemas, input validation, and output contracts.", ["pydantic", "json_schema"], "semantic", "specialist"),
    _agent("mcp-integration-specialist", "integration", "Designs MCP tool adapters, handshakes, fallbacks, and runtime diagnostics.", ["mcp", "ruflo_mcp"], "episodic", "specialist"),
    _agent("agent-a2a-coordinator", "orchestration", "Defines agent-to-agent handoff contracts, conflict rules, and shared context boundaries.", ["workflow_registry", "memory_stats"], "semantic", "specialist"),
    _agent("crewai-architect", "orchestration", "Assesses when CrewAI is the right implementation layer for role-based agent teams.", ["agent_blueprints", "crewai"], "semantic", "specialist"),
    _agent("swarms-architect", "orchestration", "Assesses when Swarms is the right implementation layer for large parallel agent groups.", ["agent_blueprints", "swarms"], "semantic", "specialist"),
    _agent("firecrawl-researcher", "integration", "Plans Firecrawl usage for web collection, extraction, and source governance.", ["firecrawl", "source_allowlist"], "semantic", "specialist"),
    _agent("vector-db-engineer", "rag", "Chooses and configures vector database adapters and indexing strategies.", ["pinecone", "chromadb", "faiss", "qdrant", "weaviate"], "semantic", "specialist"),
    _agent("embedding-specialist", "rag", "Designs embedding models, dimensions, similarity checks, and refresh strategy.", ["embedding_cache", "retrieval_evals"], "semantic", "specialist"),
    _agent("hybrid-search-engineer", "rag", "Designs hybrid lexical and semantic retrieval with metadata filters.", ["hybrid_search", "metadata_filters"], "semantic", "specialist"),
    _agent("reranking-specialist", "rag", "Designs reranking stages, evaluation criteria, and latency budgets.", ["rerankers", "retrieval_evals"], "semantic", "specialist"),
    _agent("context-compression-specialist", "rag", "Designs context compression and token-efficient evidence packaging.", ["context_compression", "token_budget"], "semantic", "specialist"),
    _agent("parent-child-retrieval-engineer", "rag", "Designs parent-child retrieval structures for precise chunks with rich context.", ["chunking", "retrieval_evals"], "semantic", "specialist"),
    _agent("graph-rag-engineer", "rag", "Designs GraphRAG entities, relationships, traversal, and citation strategy.", ["graph_rag", "knowledge_graph"], "semantic", "specialist"),
    _agent("knowledge-governance", "rag", "Defines knowledge freshness, source permissions, provenance, and deprecation rules.", ["source_registry", "guardrails"], "semantic", "specialist"),
    _agent("data-quality-analyst", "data", "Profiles datasets, missingness, duplicates, schema drift, and outlier policy.", ["dataset_treatment", "quality_gates"], "semantic", "specialist"),
    _agent("data-contract-auditor", "data", "Audits data contracts, lineage, ownership, and validation completeness.", ["data_contract", "lineage"], "semantic", "specialist"),
    _agent("feature-engineering-specialist", "ml", "Designs features, transformations, leakage checks, and feature documentation.", ["feature_store", "statistics"], "semantic", "specialist"),
    _agent("ml-baseline-engineer", "ml", "Builds baseline modeling plans, comparison criteria, and release thresholds.", ["model_service", "mlflow"], "semantic", "specialist"),
    _agent("model-evaluation-specialist", "ml", "Defines offline metrics, confidence intervals, slice analysis, and risk checks.", ["eval_service", "statistics"], "semantic", "specialist"),
    _agent("drift-monitoring-specialist", "ml", "Designs drift monitoring, alert thresholds, and retraining triggers.", ["monitoring_plan", "mlflow"], "semantic", "specialist"),
    _agent("mlflow-ops-specialist", "ml", "Maintains MLflow experiment tracking, registry aliases, and model promotion flow.", ["mlflow", "model_registry"], "episodic", "specialist"),
    _agent("model-card-reviewer", "ml", "Reviews model cards for intended use, limitations, metrics, and rollback readiness.", ["model_card", "release_checklist"], "episodic", "specialist"),
    _agent("statistics-reviewer", "analytics", "Reviews statistical assumptions, sampling, uncertainty, and metric interpretation.", ["statistics", "notebooks"], "semantic", "specialist"),
    _agent("math-for-ml-specialist", "analytics", "Checks mathematical assumptions for optimization, similarity, loss functions, and uncertainty.", ["math_notebooks", "metrics"], "semantic", "specialist"),
    _agent("privacy-lgpd-reviewer", "security", "Reviews privacy, PII handling, retention, consent, and LGPD risks.", ["pii_scan", "policy"], "semantic", "specialist"),
    _agent("threat-modeling-specialist", "security", "Models abuse cases, prompt injection, tool misuse, and deployment threats.", ["threat_model", "guardrails"], "semantic", "specialist"),
    _agent("policy-guardrails-engineer", "security", "Implements policy gates, safe autonomy boundaries, and approval rules.", ["guardrails", "authorization"], "semantic", "specialist"),
    _agent("cost-optimizer", "operations", "Optimizes model routing, token budgets, caching, and parallel execution cost.", ["cost_tracking", "model_routing"], "episodic", "specialist"),
    _agent("latency-optimizer", "operations", "Optimizes retrieval, model calls, batching, and workflow latency.", ["latency_metrics", "performance_tests"], "episodic", "specialist"),
    _agent("token-budget-analyst", "operations", "Defines token budgets, compression rules, and context allocation per agent.", ["token_tracking", "context_policy"], "episodic", "specialist"),
    _agent("structured-logging-engineer", "operations", "Designs structured logs, trace fields, redaction, and operational diagnostics.", ["structured_logs", "observability"], "episodic", "specialist"),
    _agent("metrics-instrumentation", "operations", "Defines metrics, dashboards, quality signals, and health checks.", ["metrics", "dashboards"], "episodic", "specialist"),
    _agent("ci-cd-release-manager", "platform", "Plans CI/CD gates, environment promotion, release checks, and rollback.", ["ci_cd", "release_checklist"], "episodic", "specialist"),
    _agent("container-platform-engineer", "platform", "Maintains Docker, runtime config, and deployment portability.", ["docker", "deployment"], "episodic", "specialist"),
    _agent("database-architect", "backend", "Designs database schemas, migrations, storage boundaries, and performance constraints.", ["sqlalchemy", "alembic"], "semantic", "specialist"),
    _agent("api-contract-reviewer", "backend", "Reviews API contracts, schemas, errors, auth, and backward compatibility.", ["fastapi", "pydantic"], "episodic", "specialist"),
    _agent("frontend-ux-reviewer", "frontend", "Reviews workflows, UI density, navigation, and operator ergonomics.", ["nextjs", "design_review"], "episodic", "specialist"),
    _agent("accessibility-reviewer", "frontend", "Reviews accessibility, keyboard flows, contrast, semantics, and responsive behavior.", ["a11y", "ui_tests"], "episodic", "specialist"),
    _agent("qa-adversarial-tester", "quality", "Designs adversarial tests for prompts, tools, RAG, APIs, and permissions.", ["pytest", "prompt_evals"], "episodic", "specialist"),
    _agent("regression-test-engineer", "quality", "Maintains regression suites, contract tests, and release risk checks.", ["pytest", "quality_gates"], "episodic", "specialist"),
    _agent("docs-runbook-writer", "docs", "Writes operator runbooks, incident notes, and project-specific procedures.", ["runbooks", "checklists"], "episodic", "specialist"),
    _agent("business-value-analyst", "product", "Connects project outputs to business metrics, ROI, adoption, and acceptance criteria.", ["acceptance_criteria", "metrics"], "semantic", "specialist"),
]

AGENT_CATALOG: list[dict[str, object]] = CORE_AGENT_CATALOG + SPECIALIST_AGENT_CATALOG
